### PR TITLE
Repair `zsh` Path Permissions on `oh-my-zsh` Startup under Cygwin

### LINKED ISSUE #630: compdef: unknown command or service: git
zsh 4.3.12
lastest clone of oh-my-zsh

After manually installing it (not using the wget method) whenever I login I get a load of code outputted to iterm2.

```
compdump () {
    # undefined
    builtin autoload -XUz
}
compinit () {
    emulate -L zsh
    setopt extendedglob
    typeset _i_dumpfile _i_files _i_line _i_done _i_dir _i_autodump=1
    typeset _i_tag _i_file _i_addfiles _i_fail=ask _i_check=yes _i_name
    while [[ $# -gt 0 && $1 = -[dDiuC] ]]
    do
        case "$1" in
            (-d) _i_autodump=1 
                shift
                if [[ $# -gt 0 && "$1" != -[dfQC] ]]
                then
                    _i_dumpfile="$1" 
                    shift
                fi ;;
            (-D) _i_autodump=0 
                shift ;;
            (-i) _i_fail=ign 
                shift ;;
            (-u) _i_fail=use 
                shift ;;
            (-C) _i_check= 
                shift ;;
        esac
    done
    typeset -gA _comps _services _patcomps _postpatcomps
    typeset -gA _compautos
    typeset -gA _lastcomp
    if [[ -n $_i_dumpfile ]]
    then
        typeset -g _comp_dumpfile="$_i_dumpfile"
    else
        typeset -g _comp_dumpfile="${ZDOTDIR:-$HOME}/.zcompdump"
    fi
    typeset -ga _comp_options
    _comp_options=(bareglobqual extendedglob glob multibyte nullglob rcexpandparam unset NO_allexport NO_aliases NO_cshnullglob NO_cshjunkiequotes NO_errexit NO_globsubst NO_histsubstpattern NO_ignorebraces NO_kshglob NO_ksharrays NO_kshtypeset NO_markdirs NO_octalzeroes NO_shwordsplit NO_shglob NO_warncreateglobal) 
    typeset -g _comp_setup='local -A _comp_caller_options;
             _comp_caller_options=(${(kv)options});
             setopt localoptions localtraps ${_comp_options[@]};
             local IFS=$'\'\ \\t\\r\\n\\0\''
             exec </dev/null;
             trap - ZERR
             local -a reply
             local REPLY'
    typeset -ga compprefuncs comppostfuncs
    compprefuncs=() 
    comppostfuncs=() 
    : $funcstack
    compdef () {
        local opt autol type func delete eval new i ret=0 cmd svc
        local -a match mbegin mend
        emulate -L zsh
        setopt extendedglob
        if (( ! $# ))
        then
            print -u2 "$0: I need arguments"
            return 1
        fi
        while getopts "anpPkKde" opt
        do
            case "$opt" in
                (a) autol=yes  ;;
                (n) new=yes  ;;
                ([pPkK]) if [[ -n "$type" ]]
                    then
                        print -u2 "$0: type already set to $type"
                        return 1
                    fi
                    if [[ "$opt" = p ]]
                    then
                        type=pattern 
                    elif [[ "$opt" = P ]]
                    then
                        type=postpattern 
                    elif [[ "$opt" = K ]]
                    then
                        type=widgetkey 
                    else
                        type=key 
                    fi ;;
                (d) delete=yes  ;;
                (e) eval=yes  ;;
            esac
        done
        shift OPTIND-1
        if (( ! $# ))
        then
            print -u2 "$0: I need arguments"
            return 1
        fi
        if [[ -z "$delete" ]]
        then
            if [[ -z "$eval" ]] && [[ "$1" = *\=* ]]
            then
                while (( $# ))
                do
                    if [[ "$1" = *\=* ]]
                    then
                        cmd="${1%%\=*}" 
                        svc="${1#*\=}" 
                        func="$_comps[${_services[(r)$svc]:-$svc}]" 
                        [[ -n ${_services[$svc]} ]] && svc=${_services[$svc]} 
                        [[ -z "$func" ]] && func="${${_patcomps[(K)$svc][1]}:-${_postpatcomps[(K)$svc][1]}}" 
                        if [[ -n "$func" ]]
                        then
                            _comps[$cmd]="$func" 
                            _services[$cmd]="$svc" 
                        else
                            print -u2 "$0: unknown command or service: $svc"
                            ret=1 
                        fi
                    else
                        print -u2 "$0: invalid argument: $1"
                        ret=1 
                    fi
                    shift
                done
                return ret
            fi
            func="$1" 
            [[ -n "$autol" ]] && autoload -Uz "$func"
            shift
            case "$type" in
                (widgetkey) while [[ -n $1 ]]
                    do
                        if [[ $# -lt 3 ]]
                        then
                            print -u2 "$0: compdef -K requires <widget> <comp-widget> <key>"
                            return 1
                        fi
                        [[ $1 = _* ]] || 1="_$1" 
                        [[ $2 = .* ]] || 2=".$2" 
                        [[ $2 = .menu-select ]] && zmodload -i zsh/complist
                        zle -C "$1" "$2" "$func"
                        if [[ -n $new ]]
                        then
                            bindkey "$3" | read -A opt
                            [[ $opt[-1] = undefined-key ]] && bindkey "$3" "$1"
                        else
                            bindkey "$3" "$1"
                        fi
                        shift 3
                    done ;;
                (key) if [[ $# -lt 2 ]]
                    then
                        print -u2 "$0: missing keys"
                        return 1
                    fi
                    if [[ $1 = .* ]]
                    then
                        [[ $1 = .menu-select ]] && zmodload -i zsh/complist
                        zle -C "$func" "$1" "$func"
                    else
                        [[ $1 = menu-select ]] && zmodload -i zsh/complist
                        zle -C "$func" ".$1" "$func"
                    fi
                    shift
                    for i
                    do
                        if [[ -n $new ]]
                        then
                            bindkey "$i" | read -A opt
                            [[ $opt[-1] = undefined-key ]] || continue
                        fi
                        bindkey "$i" "$func"
                    done ;;
                (*) while (( $# ))
                    do
                        if [[ "$1" = -N ]]
                        then
                            type=normal 
                        elif [[ "$1" = -p ]]
                        then
                            type=pattern 
                        elif [[ "$1" = -P ]]
                        then
                            type=postpattern 
                        else
                            case "$type" in
                                (pattern) if [[ $1 = (#b)(*)=(*) ]]
                                    then
                                        _patcomps[$match[1]]="=$match[2]=$func" 
                                    else
                                        _patcomps[$1]="$func" 
                                    fi ;;
                                (postpattern) if [[ $1 = (#b)(*)=(*) ]]
                                    then
                                        _postpatcomps[$match[1]]="=$match[2]=$func" 
                                    else
                                        _postpatcomps[$1]="$func" 
                                    fi ;;
                                (*) if [[ "$1" = *\=* ]]
                                    then
                                        cmd="${1%%\=*}" 
                                        svc=yes 
                                    else
                                        cmd="$1" 
                                        svc= 
                                    fi
                                    if [[ -z "$new" || -z "${_comps[$1]}" ]]
                                    then
                                        _comps[$cmd]="$func" 
                                        [[ -n "$svc" ]] && _services[$cmd]="${1#*\=}" 
                                    fi ;;
                            esac
                        fi
                        shift
                    done ;;
            esac
        else
            case "$type" in
                (pattern) unset "_patcomps[$^@]" ;;
                (postpattern) unset "_postpatcomps[$^@]" ;;
                (key) print -u2 "$0: cannot restore key bindings"
                    return 1 ;;
                (*) unset "_comps[$^@]" ;;
            esac
        fi
    }
    typeset _i_wdirs _i_wfiles
    _i_wdirs=() 
    _i_wfiles=() 
    autoload -Uz compaudit
    if [[ -n "$_i_check" ]]
    then
        typeset _i_q
        if ! eval compaudit
        then
            if [[ -n "$_i_q" ]]
            then
                if [[ "$_i_fail" = ask ]]
                then
                    if ! read -q "?zsh compinit: insecure $_i_q, run compaudit for list.
Ignore insecure $_i_q and continue [y] or abort compinit [n]? "
                    then
                        print -u2 "$0: initialization aborted"
                        unfunction compinit compdef
                        unset _comp_dumpfile _comp_secure compprefuncs comppostfuncs _comps _patcomps _postpatcomps _compautos _lastcomp
                        return 1
                    fi
                    _i_wfiles=() 
                    _i_wdirs=() 
                else
                    (( $#_i_wfiles )) && _i_files=("${(@)_i_files:#(${(j:|:)_i_wfiles%.zwc})}") 
                    (( $#_i_wdirs )) && _i_files=("${(@)_i_files:#(${(j:|:)_i_wdirs%.zwc})/*}") 
                fi
            fi
            typeset -g _comp_secure=yes
        fi
    fi
    autoload -Uz compdump compinstall
    _i_done='' 
    if [[ -f "$_comp_dumpfile" ]]
    then
        if [[ -n "$_i_check" ]]
        then
            read -rA _i_line < "$_comp_dumpfile"
            if [[ _i_autodump -eq 1 && $_i_line[2] -eq $#_i_files && $ZSH_VERSION = $_i_line[4] ]]
            then
                builtin . "$_comp_dumpfile"
                _i_done=yes 
            fi
        else
            builtin . "$_comp_dumpfile"
            _i_done=yes 
        fi
    fi
    if [[ -z "$_i_done" ]]
    then
        typeset -A _i_test
        for _i_dir in $fpath
        do
            [[ $_i_dir = . ]] && continue
            (( $_i_wdirs[(I)$_i_dir] )) && continue
            for _i_file in $_i_dir/^([^_]*|*~|*.zwc)(N)
            do
                _i_name="${_i_file:t}" 
                (( $+_i_test[$_i_name] + $_i_wfiles[(I)$_i_file] )) && continue
                _i_test[$_i_name]=yes 
                read -rA _i_line < $_i_file
                _i_tag=$_i_line[1] 
                shift _i_line
                case $_i_tag in
                    (\#compdef) if [[ $_i_line[1] = -[pPkK](n|) ]]
                        then
                            compdef ${_i_line[1]}na "${_i_name}" "${(@)_i_line[2,-1]}"
                        else
                            compdef -na "${_i_name}" "${_i_line[@]}"
                        fi ;;
                    (\#autoload) autoload -Uz "$_i_line[@]" ${_i_name}
                        [[ "$_i_line" != \ # ]] && _compautos[${_i_name}]="$_i_line"  ;;
                esac
            done
        done
        if [[ $_i_autodump = 1 ]]
        then
            compdump
        fi
    fi
    for _i_line in complete-word delete-char-or-list expand-or-complete expand-or-complete-prefix list-choices menu-complete menu-expand-or-complete reverse-menu-complete
    do
        zle -C $_i_line .$_i_line _main_complete
    done
    zle -la menu-select && zle -C menu-select .menu-select _main_complete
    bindkey '^i' | read -A _i_line
    if [[ ${_i_line[2]} = expand-or-complete ]] && zstyle -a ':completion:' completer _i_line && (( ${_i_line[(i)_expand]} <= ${#_i_line} ))
    then
        bindkey '^i' complete-word
    fi
    unfunction compinit compaudit
    autoload -Uz compinit compaudit
    return 0
}
compinstall () {
    # undefined
    builtin autoload -XUz
}
edit-command-line () {
    # undefined
    builtin autoload -XU
}
url-quote-magic () {
    # undefined
    builtin autoload -XU
}
compdef: unknown command or service: git
compdef: unknown command or service: git
compdef: unknown command or service: git
compdef: unknown command or service: git
compdef: unknown command or service: git
compdef: unknown command or service: git
```

Tab complete doesn't work, the git plugin seems to be working and themes are also working. This is my 5th install of oh-my-zsh and I've not seen this issue before.

### PR DESCRIPTION
**Pull request by leycec**
This pull request fixes #630 for Cygwin as well as [babun](https://github.com/babun/babun) issues [#159](https://github.com/babun/babun/issues/159), [#281](https://github.com/babun/babun/issues/281), and [#322](https://github.com/babun/babun/issues/322). For non-Cygwin platforms (e.g., Linux, OS X), this only partially addresses #630 by improving startup error reporting in a platform-independent manner. In theory, that should both improve the readability of related bug reports *and* enable end users to locally fix this issue themselves.

## The Problem

The `oh-my-zsh.sh` startup script currently caches completions as follows:

    compinit -i -d "${ZSH_COMPDUMP}"

**That's a problem.** The `-i` option instructs `compinit()` to silently ignore all top-level completion-dependent directories having insecure permissions and/or ownership, typically resulting in an effectively empty `.zcompdump` file [*read:* on the order of 160B rather than the expected 32KB]. That, in turn, results in insanely obscure, non-human-readable output on `oh-my-zsh` startup resembling:

```
add-zsh-hook () {
emulate -L zsh
local -a hooktypes
hooktypes=(chpwd precmd preexec periodic zshaddhistory zshexit zsh_directory_name)
local usage="Usage: $0 hook function\nValid hooks are:\n $hooktypes"
local opt
local -a autoopts
integer del list help
while getopts "dDhLUzk" opt
do
case $opt in
(d) del=1 ;;
(D) del=2 ;;
(h) help=1 ;;
(L) list=1 ;;
([Uzk]) autoopts+=(-$opt) ;;
() return 1 ;;
esac
done
shift $(( OPTIND - 1 ))
if (( list ))
then
typeset -mp "(${1:-${(@j:|:)hooktypes}})_functions"
return $?
elif (( help || $# != 2 || ${hooktypes[(I)$1]} == 0 ))
then
print -u$(( 2 - help )) $usage
return $(( 1 - help ))
fi
local hook="${1}_functions"
local fn="$2"
if (( del ))
then
if (( ${(P)+hook} ))
then
if (( del == 2 ))
then
set -A $hook ${(P)hook:#${~fn}}
else
set -A $hook ${(P)hook:#$fn}
fi
if (( ! ${(P)#hook} ))
then
unset $hook
fi
fi
else
if (( ${(P)+hook} ))
then
if (( ${${(P)hook}[(I)$fn]} == 0 ))
then
set -A $hook ${(P)hook} $fn
fi
else
set -A $hook $fn
fi
autoload $autoopts -- $fn
fi
}
compdump () {
# undefined
builtin autoload -XUz
}
compinit () {
emulate -L zsh
setopt extendedglob
typeset _i_dumpfile _i_files _i_line _i_done _i_dir _i_autodump=1
typeset _i_tag _i_file _i_addfiles _i_fail=ask _i_check=yes _i_name
while [[ $# -gt 0 && $1 = -[dDiuC] ]]
do
case "$1" in
(-d) _i_autodump=1
shift
if [[ $# -gt 0 && "$1" != -[dfQC] ]]
then
_i_dumpfile="$1"
shift
fi ;;
(-D) _i_autodump=0
shift ;;
(-i) _i_fail=ign
shift ;;
(-u) _i_fail=use
shift ;;
(-C) _i_check=
shift ;;
esac
done
typeset -gA _comps _services _patcomps _postpatcomps
typeset -gA _compautos
typeset -gA _lastcomp
if [[ -n $_i_dumpfile ]]
then
typeset -g _comp_dumpfile="$_i_dumpfile"
else
typeset -g _comp_dumpfile="${ZDOTDIR:-$HOME}/.zcompdump"
fi
typeset -ga _comp_options
_comp_options=(bareglobqual extendedglob glob multibyte nullglob rcexpandparam unset NO_allexport NO_aliases NO_cshnullglob NO_cshjunkiequotes NO_errexit NO_globsubst NO_histsubstpattern NO_ignorebraces NO_ignoreclosebraces NO_kshglob NO_ksharrays NO_kshtypeset NO_markdirs NO_octalzeroes NO_shwordsplit NO_shglob NO_warncreateglobal)
typeset -g _comp_setup='local -A _comp_caller_options;
_comp_caller_options=(${(kv)options[@]});
setopt localoptions localtraps ${_comp_options[@]};
local IFS=$'\'\ \t\r\n\0\''
exec </dev/null;
trap - ZERR
local -a reply
local REPLY'
typeset -ga compprefuncs comppostfuncs
compprefuncs=()
comppostfuncs=()
: $funcstack
compdef () {
local opt autol type func delete eval new i ret=0 cmd svc
local -a match mbegin mend
emulate -L zsh
setopt extendedglob
if (( ! $# ))
then
print -u2 "$0: I need arguments"
return 1
fi
while getopts "anpPkKde" opt
do
case "$opt" in
(a) autol=yes ;;
(n) new=yes ;;
([pPkK]) if [[ -n "$type" ]]
then
print -u2 "$0: type already set to $type"
return 1
fi
if [[ "$opt" = p ]]
then
type=pattern
elif [[ "$opt" = P ]]
then
type=postpattern
elif [[ "$opt" = K ]]
then
type=widgetkey
else
type=key
fi ;;
(d) delete=yes ;;
(e) eval=yes ;;
esac
done
shift OPTIND-1
if (( ! $# ))
then
print -u2 "$0: I need arguments"
return 1
fi
if [[ -z "$delete" ]]
then
if [[ -z "$eval" ]] && [[ "$1" = *\= ]]
then
while (( $# ))
do
if [[ "$1" = \= ]]
then
cmd="${1%%\=}"
svc="${1#\=}"
func="$comps[${_services[(r)$svc]:-$svc}]"
[[ -n ${_services[$svc]} ]] && svc=${_services[$svc]}
[[ -z "$func" ]] && func="${${_patcomps[(K)$svc][1]}:-${_postpatcomps[(K)$svc][1]}}"
if [[ -n "$func" ]]
then
_comps[$cmd]="$func"
_services[$cmd]="$svc"
else
print -u2 "$0: unknown command or service: $svc"
ret=1
fi
else
print -u2 "$0: invalid argument: $1"
ret=1
fi
shift
done
return ret
fi
func="$1"
[[ -n "$autol" ]] && autoload -Uz "$func"
shift
case "$type" in
(widgetkey) while [[ -n $1 ]]
do
if [[ $# -lt 3 ]]
then
print -u2 "$0: compdef -K requires "
return 1
fi
[[ $1 = _* ]] || 1="$1"
[[ $2 = .* ]] || 2=".$2"
[[ $2 = .menu-select ]] && zmodload -i zsh/complist
zle -C "$1" "$2" "$func"
if [[ -n $new ]]
then
bindkey "$3" | IFS=$' \t' read -A opt
[[ $opt[-1] = undefined-key ]] && bindkey "$3" "$1"
else
bindkey "$3" "$1"
fi
shift 3
done ;;
(key) if [[ $# -lt 2 ]]
then
print -u2 "$0: missing keys"
return 1
fi
if [[ $1 = .* ]]
then
[[ $1 = .menu-select ]] && zmodload -i zsh/complist
zle -C "$func" "$1" "$func"
else
[[ $1 = menu-select ]] && zmodload -i zsh/complist
zle -C "$func" ".$1" "$func"
fi
shift
for i
do
if [[ -n $new ]]
then
bindkey "$i" | IFS=$' \t' read -A opt
[[ $opt[-1] = undefined-key ]] || continue
fi
bindkey "$i" "$func"
done ;;
() while (( $# ))
do
if [[ "$1" = -N ]]
then
type=normal
elif [[ "$1" = -p ]]
then
type=pattern
elif [[ "$1" = -P ]]
then
type=postpattern
else
case "$type" in
(pattern) if [[ $1 = (#b)()=() ]]
then
_patcomps[$match[1]]="=$match[2]=$func"
else
_patcomps[$1]="$func"
fi ;;
(postpattern) if [[ $1 = (#b)()=() ]]
then
_postpatcomps[$match[1]]="=$match[2]=$func"
else
_postpatcomps[$1]="$func"
fi ;;
() if [[ "$1" = \= ]]
then
cmd="${1%%\=}"
svc=yes
else
cmd="$1"
svc=
fi
if [[ -z "$new" || -z "${_comps[$1]}" ]]
then
_comps[$cmd]="$func"
[[ -n "$svc" ]] && _services[$cmd]="${1#\=}"
fi ;;
esac
fi
shift
done ;;
esac
else
case "$type" in
(pattern) unset "patcomps[$^@]" ;;
(postpattern) unset "_postpatcomps[$^@]" ;;
(key) print -u2 "$0: cannot restore key bindings"
return 1 ;;
() unset "_comps[$^@]" ;;
esac
fi
}
typeset _i_wdirs _i_wfiles
_i_wdirs=()
_i_wfiles=()
autoload -Uz compaudit
if [[ -n "$_i_check" ]]
then
typeset _i_q
if ! eval compaudit
then
if [[ -n "$_i_q" ]]
then
if [[ "$_i_fail" = ask ]]
then
if ! read -q "?zsh compinit: insecure $_i_q, run compaudit for list.
Ignore insecure $_i_q and continue [y] or abort compinit [n]? "
then
print -u2 "$0: initialization aborted"
unfunction compinit compdef
unset _comp_dumpfile _comp_secure compprefuncs comppostfuncs _comps _patcomps _postpatcomps _compautos _lastcomp
return 1
fi
_i_wfiles=()
_i_wdirs=()
else
(( $#_i_wfiles )) && _i_files=("${(@)_i_files:#(${(j:|:)_i_wfiles%.zwc})}")
(( $#_i_wdirs )) && _i_files=("${(@)_i_files:#(${(j:|:)_i_wdirs%.zwc})/}")
fi
fi
typeset -g _comp_secure=yes
fi
fi
autoload -Uz compdump compinstall
_i_done=''
if [[ -f "$_comp_dumpfile" ]]
then
if [[ -n "$_i_check" ]]
then
IFS=$' \t' read -rA _i_line < "$_comp_dumpfile"
if [[ _i_autodump -eq 1 && $_i_line[2] -eq $#_i_files && $ZSH_VERSION = $_i_line[4] ]]
then
builtin . "$_comp_dumpfile"
_i_done=yes
fi
else
builtin . "$_comp_dumpfile"
_i_done=yes
fi
fi
if [[ -z "$_i_done" ]]
then
typeset -A _i_test
for _i_dir in $fpath
do
[[ $_i_dir = . ]] && continue
(( $_i_wdirs[(I)$_i_dir] )) && continue
for _i_file in $_i_dir/^([^]|~|*.zwc)(N)
do
_i_name="${_i_file:t}"
(( $+_i_test[$_i_name] + $_i_wfiles[(I)$_i_file] )) && continue
_i_test[$_i_name]=yes
IFS=$' \t' read -rA _i_line < $_i_file
_i_tag=$_i_line[1]
shift _i_line
case $_i_tag in
(#compdef) if [[ $_i_line[1] = -pPkK ]]
then
compdef ${_i_line[1]}na "${_i_name}" "${(@)_i_line[2,-1]}"
else
compdef -na "${_i_name}" "${_i_line[@]}"
fi ;;
(#autoload) autoload -Uz "$_i_line[@]" ${_i_name}
[[ "$_i_line" != \ # ]] && _compautos[${_i_name}]="$_i_line" ;;
esac
done
done
if [[ $_i_autodump = 1 ]]
then
compdump
fi
fi
for _i_line in complete-word delete-char-or-list expand-or-complete expand-or-complete-prefix list-choices menu-complete menu-expand-or-complete reverse-menu-complete
do
zle -C $_i_line .$_i_line _main_complete
done
zle -la menu-select && zle -C menu-select .menu-select _main_complete
bindkey '^i' | IFS=$' \t' read -A _i_line
if [[ ${_i_line[2]} = expand-or-complete ]] && zstyle -a ':completion:' completer _i_line && (( ${_i_line[(i)_expand]} <= ${#_i_line} ))
then
bindkey '^i' complete-word
fi
unfunction compinit compaudit
autoload -Uz compinit compaudit
return 0
}
compinstall () {
# undefined
builtin autoload -XUz
}
edit-command-line () {
# undefined
builtin autoload -XU
}
url-quote-magic () {
# undefined
builtin autoload -XU
}
compdef: unknown command or service: git
compdef: unknown command or service: git
compdef: unknown command or service: git
compdef: unknown command or service: git
compdef: unknown command or service: git
compdef: unknown command or service: git
compdef: unknown command or service: git
```

Which is almost worse than no output at all. Eliminating the `-i` option to `compinit()` reveals the underlying issue: 

    zsh compinit: insecure directories, run compaudit for list.
    Ignore insecure directories and continue [y] or abort compinit [n]?

**Ah ha!** Running `compaudit()` yields output resembling:

     There are insecure directories:
     /home/Administrator/.oh-my-zsh/plugins/git
     /usr/share/zsh/site-functions
     /usr/share/zsh/5.0.6/functions
     /home/Administrator/.oh-my-zsh/plugins
     /home/Administrator/.oh-my-zsh
     /usr/share/zsh
     /usr/share/zsh/5.0.6

So basically everything then? **Yup.** Under Cygwin, *all* top-level `zsh` directories are installed with insecure permissions enabling group writability. This is a [well-known issue](http://blog.en.edaro.net/2014/01/fix-broken-autocompletion-with-zsh-in.html) with [well-known one-liner fixes](http://www.wezm.net/technical/2008/09/zsh-cygwin-and-insecure-directories/).

In short, there are a number of interlocking issues with `oh-my-zsh.sh`'s completion initialization. Insecure path permissions are hidden rather than listed, preventing sane debugging and issue resolution. Cygwin seemingly *always* installs `zsh` with insecure path permissions, significantly exacerbating this issue on that platform.

## The Solution

If insecure path permissions are detected at `oh-my-zsh` startup:

* Under all platforms including Cygwin:
   * Insecure paths are now explicitly listed to the user *before* completions are initialized.
   * If the current terminal is interactive, the `-i` option is no longer passed to `compinit()`. This instructs `zsh` to query the user as to whether these paths should be ignored *or* completions left unitialized. (See the above prompt.)
* Under Cygwin, if the current terminal is interactive, `oh-my-zsh` now queries the user as to whether these paths should be automatically repaired. Since the core problem is insecure group writability, the solution is to simply disable group writability for all problematic directories with magical one-liner magic. (*It's magical!*)

Thus dies another bug in the night.

### CODE REVIEW

**Comment by mcornella** [comment]
Hey @leycec thank you for taking the time to diagnose this issue and craft this self-explanatory PR. I just now saw it but you made it really easy for me to put my _Seal of Approval™_ right here: :+1: :shipit: 

/cc @robbyrussell

**Comment by mcornella** [comment]
Oh, btw, I think the check for interactive shell can be simplified with `[[ -o interactive ]]`, similarly to how the `[[ -o login ]]` is used to check for login shells. See [Conditional Expressions](http://zsh.sourceforge.net/Doc/Release/Conditional-Expressions.html) for the `-o` switch and the [`interactive` option](http://zsh.sourceforge.net/Doc/Release/Options.html#index-INTERACTIVE).

**Comment by leycec** [comment]
> Hey @leycec thank you for taking the time to diagnose this issue and craft this self-explanatory PR.

This is where I get to say, "No, thank *you*." You guys are great! And thanks for the instructive feedback, too.

> Oh, btw, I think the check for interactive shell can be simplified with [[ -o interactive ]], similarly to how the [[ -o login ]] is used to check for login shells. See Conditional Expressions for the -o switch and the interactive option.

**Right.** I definitely contemplated reducing `[[ -t 0 && -t 1 ]]` to just `[[ -o interactive ]]`, as you astutely suggest. I should've probably commented why I *didn't* do that – because the current test is actually intentional.

I've been burned by `[[ -o interactive ]]` on more than one occasion. The issue is a bit subtle. That test only queries a shell option set at shell startup and hence returns false positives in edge cases: e.g.,

    >>> [[ -o interactive ]] && print "Interactive shells are interactive."
    Interactive shells are interactive.
    >>> print "$([[ -o interactive ]] && print "So are non-interactive command substitutions! Wait. What?")"
    So are non-interactive command substitutions! Wait. What?

Since this pull request patches the top-level `oh-my-zsh.sh` script, it seemed pretty important to safeguard against that sort of nonsense. Who knows? That script *could* conceivably be sourced under oddball circumstances (e.g., command substitutions). Sure, it probably won't happen. Like, *ever*. But if it does, the more accurate test `[[ -t 0 && -t 1 ]]` *should* help us out.

**Anyway.** This is totally pedantic, so I'd be happy to go either way.

**Comment by mcornella** [comment]
Ok that's really clever. I'm all for safeguarding our asses. Let me find some time to test this out thoroughly and it'll hopefully be merged in less than a week.

@apjanke: you had a cygwin shell available, can you test this out?

File: oh-my-zsh.sh [hunk 1]
```diff
@@ -59,9 +59,54 @@ if [ -z "$ZSH_COMPDUMP" ]; then
...
+#     /usr/share/zsh/5.0.6
+#
+# Silently detect and, in a few well-known cases, offer to fix this issue.
+if ! compaudit &>/dev/null; then
+  # Print this list of insecure directories.
+  compaudit
+  print
+
+  # If this is Cygwin *and* both standard input and output are connected to an
+  # interactive terminal, offer to fix this. Cygwin has a long-standing bug in
```
Comment (ncanceill) [inline oh-my-zsh.sh]: This all looks awesome!

One little thing: could you please find a reference to that _"long-standing bug"_ and include it in the comment?

I found [this](http://www.wezm.net/technical/2008/09/zsh-cygwin-and-insecure-directories/) but I am more looking for something about Cygwin messing up permission on those directories.

Comment (mcornella) [inline oh-my-zsh.sh]: There is this one in the mailing list: [Zsh completion problem](https://www.cygwin.com/ml/cygwin/2011-03/msg00748.html) but it looks like [it was solved](https://www.cygwin.com/ml/cygwin-announce/2011-01/msg00006.html).

Also, [in this blog post](http://blog.en.edaro.net/2014/01/fix-broken-autocompletion-with-zsh-in.html) the author says this one-liner didn't fix it for him because, basically, the Windows ACLs weren't properly set up for the user that run cygwin.

So it looks to me that this PR will need a little more testing. @leycec can you direct some babun users this way? Let's see if they can confirm this solves compinit problems in a fresh installation of babun/cygwin.

**Comment by apjanke** [comment]
Sorry for delay on this. I do have cygwin with OMZ running on it, but my Windows `git` is bunged up at the moment. Will test when I have it sorted out.

FWIW, my Cygwin `zsh` installations do not have the permissions issue noted here; those dirs are all `rwxr-xr-x` on my Windows 7 boxes. I'll open them up for one of the test runs though, so I can see what happens in both cases.

File: oh-my-zsh.sh (hunk 1 above)
Comment (leycec) [inline oh-my-zsh.sh]: > There is this one in the mailing list: Zsh completion problem but it looks like it was solved.

**The plot thickens.** For sanity, Babun forces use of the most recently released of Cygwin (2.0.4, as of this thick-headed writing). I'm happy to personally confirm that this issue is no longer solved, probably due to an undetected regression. The version of `zsh` cited in that **2011** mailing list thread (4.3.11) is obscenely obsolete. The long road to `zsh` 5.0.0 appears to have reintroduced this issue... *in stealth mode*.

But don't take my greasy word for it:

* Similar [Stackoverflow question](https://superuser.com/questions/489831/zsh-autocompletion-not-working-on-cygwin). **2012** >= 2011.
* Similar [`oh-my-cygwin` issue](https://github.com/haithembelhaj/oh-my-cygwin/issues/1). **2013**  >= 2011.
* Similar [Stackoverflow question](https://stackoverflow.com/questions/13762280/zsh-compinit-insecure-directories/22753363#22753363). **2014** >= 2011.
* Similar [`zsh` mailing list issue](http://www.zsh.org/mla/users/2014/msg00820.html). **2014** >= 2011.

Alternately, peruse user comments for the issues listed above in the pull request description. By inspection, this issue *clearly* remains unresolved.

> Also, in this blog post the author says this one-liner didn't fix it for him because, basically, the Windows ACLs weren't properly set up for the user that run cygwin.

Fair enough! Where there exists a discrepancy between the account with which Babun and/or Cygwin was installed (typically, Administrator) and the account attempting to use Babun and/or Cygwin, the provided solution may be insufficient. **But that's O.K.**

In such case, `oh-my-zsh` startup gracefully detects the failure to correct this issue and emits the non-fatal warning `"[oh-my-zsh] Unable to fix."`. This is *still* demonstrably superior to the current approach, in that the user is at least informed of the underlying issue in a human-readable manner.

This pull request is *not* intended to perfectly, completely, and finally address this issue for all users under all contexts. It *is* intended to address this issue for most Cygwin users under the simplistic assumption of parity between the account having installed and the account attempting to use Babun and/or Cygwin. This is generally the case, except where it isn't.

> So it looks to me that this PR will need a little more testing. @leycec can you direct some babun users this way? Let's see if they can confirm this solves compinit problems in a fresh installation of babun/cygwin.

That's... a good idea. By listing several Babun issues above in the pull request description, Github implicitly referenced this pull request in all such issues. Users who have commented on and hence implicitly subscribed to those issues *should* now theoretically be informed.

**Comment by leycec** [comment]
> Sorry for delay on this. I do have Cygwin with OMZ running on it, but my Windows git is bunged up at the moment. Will test when I have it sorted out.

No worries! I feel your Windows pain and reciprocate with a pensive penguin. :penguin:

> FWIW, my Cygwin zsh installations do not have the permissions issue noted here; those dirs are all rwxr-xr-x on my Windows 7 boxes. I'll open them up for one of the test runs though, so I can see what happens in both cases.

I am unastonished. As [commented above](https://github.com/robbyrussell/oh-my-zsh/pull/3889#discussion_r32593339), this issue appears to be "notoriously difficult to reproduce." On my hosted Windows XP Professional x64 guest running Babun, this issue only birthed itself *after* upgrading `zsh` from an existing Cygwin installation.

**Comment by VinzNL** [comment]
I was fortunate enough to save the broken .zcomdump-hostname-5.0.6 before fixing it manually and later finding this thread, so I can trigger it at will now.

Unfortunately, after replacing the .oh-my-zsh/oh-my-zsh.sh file, I didn't get the expected result:

```
/home/vincent/.oh-my-zsh/oh-my-zsh.sh:74: command not found: compaudit

[oh-my-zsh] Automatically fix this? [y/N] ychmod: missing operand after ‘g-w’
Try 'chmod --help' for more information.

[oh-my-zsh] Unable to fix.
/home/vincent/.oh-my-zsh/oh-my-zsh.sh:105: command not found: compinit
/home/vincent/.oh-my-zsh/plugins/git/git.plugin.zsh:78: command not found: compdef
/home/vincent/.oh-my-zsh/plugins/git/git.plugin.zsh:86: command not found: compdef
/home/vincent/.oh-my-zsh/plugins/git/git.plugin.zsh:92: command not found: compdef
/home/vincent/.oh-my-zsh/plugins/git/git.plugin.zsh:101: command not found: compdef
/home/vincent/.oh-my-zsh/plugins/git/git.plugin.zsh:106: command not found: compdef
/home/vincent/.oh-my-zsh/plugins/git/git.plugin.zsh:111: command not found: compdef
/home/vincent/.oh-my-zsh/plugins/git/git.plugin.zsh:115: command not found: compdef
/home/vincent/.oh-my-zsh/plugins/git/git.plugin.zsh:121: command not found: compdef
/home/vincent/.oh-my-zsh/plugins/git/git.plugin.zsh:126: command not found: compdef
/home/vincent/.oh-my-zsh/plugins/git/git.plugin.zsh:129: command not found: compdef
/home/vincent/.oh-my-zsh/plugins/git/git.plugin.zsh:131: command not found: compdef
/home/vincent/.oh-my-zsh/plugins/git/git.plugin.zsh:144: command not found: compdef
/home/vincent/.oh-my-zsh/plugins/git/git.plugin.zsh:155: command not found: compdef
```
It seems that when things go wrong they go really wrong, as not being able to call compaudit throws a wrench into this solution.

If anyone wants me to test anything else I can.

**Comment by apjanke** [comment]
Could you post your broken `.zcompdump` file as a gist so we can use it for forensics and reproduction, too?

I think you need to modify the script such that when `compaudit` does find something wrong, it deletes the existing `.zcompdump-XXX` file so that `compinit` regenerates it instead of just reusing the existing one, which was probably built from the bad directory state.

**Comment by apjanke** [comment]
With this, `oh-my-zsh.sh` is getting pretty long, and a large fraction of its lines are now devoted to special-case Cygwin stuff, instead of the main logic of initializing OMZ. Maybe this could go in a function in `lib/` somewhere and just get called by `oh-my-zsh.sh`?

**Comment by apjanke** [comment]
Conflicts with (and should probably auto-close) #3522.

**Comment by leycec** [comment]
Excellent stuff, guys. I have nothing but praises! No, literally. I'm enmeshed in a few pull requests elsewhere and don't quite have time tonight to address your gruelling concerns, @apjanke and @VinzNL. I *do* have time to admit that you're both correct on every count, however:

> I was fortunate enough to save the broken .zcomdump-hostname-5.0.6 in my babun install before fixing it manually and later finding this thread, so I can trigger it at will now.

**Yay!** I may politely beg to "borrow" that at some point.

> /home/vincent/.oh-my-zsh/oh-my-zsh.sh:74: command not found: compaudit

That's odd and terrible. `compaudit()` is autoloaded from the file of the same basename in the current `${FPATH}` (e.g., `/usr/share/zsh/functions/Completion/compaudit`). To my knowledge, that file's bundled with *all* `zsh` installations – including Cygwin. Your `${FPATH}` appears to be uninitialized at this point in `oh-my-zsh` startup, which is well within the realm of fugly edge-cases that this pull request should test for.

In short, we should simply test whether the `compaudit()` function exists *before* attempting to call that function. (That Murphy and his bloody Law.) I'll also need to investigate whether `oh-my-zsh` startup already attempts to initialize `${FPATH}`. (It probably does.) If so, this test should be performed *after* such initialization. Both of these things are trivial. Which means I'll probably do them!

> I just realised that I did have compaudit and compinit when I fixed this manually, before replacing my oh-my-zsh.sh. Is my test not good enough

Your test is awesome. Feel good. Be proud.

> ...or does this oh-my-zsh.sh break something?

...*yeah*. That's almost certainly the case. Thanks for playing `oh-my-zsh` guinea pig! When I get this patched up in a few days, would you mind testing this again?

> Could you post your broken .zcompdump file as a gist so we can use it for forensics and reproduction, too?

I second this sane suggestion.

> I think you need to modify the script such that when compaudit does find something wrong, it deletes the existing .zcompdump-* files so that compinit regenerates it instead of just reusing an existing one, which were probably built from the bad directory state.

I debated doing just that, but chickened out at the eleventh hour. The changeset was fairly corpulent already... and, well, I'm contemptibly lazy.

**But you're right.** That sort of general-purpose autofix will probably correct this for most non-Babun users as well. If I recall correctly, `compinit()` provides an option forcing recompilation rather than reuse of existing `.zcompdump-*` files – which, if true, would simplify my too-short life.

In any case, this will be done. (Probably. (O.K., it will.))

> (Should probably delete all of them and not just the current session's $ZSH_COMPDUMP, in case other ones were built from bad dirs too, but wouldn't be noticed because the next startup for that host/version would have a clean compaudit.)

I didn't quite follow this initially. I'm probably just on the short bus tonight.

But you're right, by God(s)! That's a clever catch. I'm in agreement that the untrustworthiness of one `.zcompdump-*` file renders *all* such files untrustworthy and hence requiring recompilation. **It shall be done, Mr. Sensible.**

> Maybe this could go in a function in lib/ somewhere and just get called by oh-my-zsh.sh?

Reasonable suggestion is reasonable. Care needs to be taken with that sort of file juggling, of course. Hopefully, `oh-my-zsh` supports such reuse that early in startup. I'm sure it does, but more research (...on my despondent part) will be needed.

In synopsis, sucks to be me. :tada:

**Comment by apjanke** [comment]
Excellent.

Hmmm. Looks like there could be insecure directories from within OMZ itself.

Here's what I get on my Windows 7 Cygwin when I run `compaudit` after OMZ is loaded. This is a repo that I created by just cloning my forked repo, and not fiddling with any permissions.

```
[@ in ~]
$ compaudit
There are insecure directories:
/home/janke/.oh-my-zsh/plugins/common-aliases
/home/janke/.oh-my-zsh/plugins/nyan
/home/janke/.oh-my-zsh/plugins/osx
/home/janke/.oh-my-zsh/completions
/home/janke/.oh-my-zsh/plugins
/home/janke/.oh-my-zsh/plugins
/home/janke/.oh-my-zsh/plugins
/home/janke/.oh-my-zsh
/home/janke/.oh-my-zsh
[✘ @ in ~]
$ ls -lad $(compaudit 2>&1 | tail -n +2 | uniq)
lrwxrwxrwx  1 janke None 27 Mar 31 16:06 /home/janke/.oh-my-zsh -> janke/opp/working/oh-my-zsh
drwxrwx---+ 1 janke None  0 May 20 20:08 /home/janke/.oh-my-zsh/completions
drwxrwx---+ 1 janke None  0 May 20 20:08 /home/janke/.oh-my-zsh/plugins
drwxrwx---+ 1 janke None  0 Feb 15 01:48 /home/janke/.oh-my-zsh/plugins/common-aliases
drwxrwx---+ 1 janke None  0 Feb 15 01:48 /home/janke/.oh-my-zsh/plugins/nyan
drwxrwx---+ 1 janke None  0 Feb 24 03:34 /home/janke/.oh-my-zsh/plugins/osx
```

Not sure how this should be handled. Some of it could be eliminated by moving this test before the plugins are added to `$fpath` at line 41. Or maybe there's no harm in `chmod g-w`-ing those in-repo directories too. Though I'm a little uncomfortable doing that; seems like taking liberties with the user's own setup.

**Comment by leycec** [comment]
> Looks like there could be insecure directories from within OMZ itself.

Code Jesus, save us now. Is the insecurity you've noted due to the `None` group (to which multiple users probably belong – because, why not? This is Cygwin.) having write access to the listed subdirectories? If so... yeah, that's insecure.

I assume this is a `umask` and/or non-existent group and/or non-existent user issue. `oh-my-zsh` startup could probably *also* be improved to:

1. Detect the current user and/or primary group not actually existing.
1. Respond by instructing the user to manually run `mkpasswd` and/or `mkgroup` after `oh-my-zsh` startup.

That's significant (and different) enough to warrant a pull request of its own, I'd say. Anyone mind if I take a rain check on that one?

> Some of it could be eliminated by moving this test before the plugins are added to $fpath at line 41.

**Right.** That'd at least clear up the `~/.oh-my-zsh` and `~/.oh-my-zsh/completions` complaints.

> Or maybe there's no harm in chmod g-w-ing those in-repo directories too. Though I'm a little uncomfortable doing that; seems like taking liberties with the user's own setup.

I'm always happy to take liberties with the user. Or their stuff.

O.K., but seriously. While I'd typically be nervous about infringing on the user's home turf, *this is Cygwin.* Thanks to the prevalence of [BLODA](https://cygwin.com/faq/faq.html#faq.using.bloda), there already exists an expectation of simple things simply not working. The insecurity you've noted strikes me as yet another nail in that dusty coffin. If `oh-my-zsh` can implicitly correct this on the user's behalf *without* introducing additional insecurities, does it not have a moral obligation to do so?

O.K., probably not. I do believe, however, that we've finally unlocked the core issue. Thanks to your report, I grepped up my own Cygwin installation. **Turns out every problem path has group ownership of `None`.**

This suggests that, contrary to me suggestion above (...I confuse me, too), we should explicitly filter the list of problem paths for paths with group ownership of `None` *before* `chmod`-ing group write access away from those paths. Paths with any other group ownership must have been intentionally changed by a user and will, under this scheme, *not* be molested.

In theoretical theory, this should alleviate both your concern of mucking around with user paths *and* the aforementioned concern of this fix failing when the current user differs from the user that installed `zsh`.

Or maybe I'm still on the short bus.

**Comment by apjanke** [comment]
Think I found why it's breaking with `command not found: compaudit`. The `autoload -U compinit` call was removed at line 63. And calling `compinit` is what marks `compaudit` and the related completion functions for autoloading.

I can reproduce @VinzNL's breakage by running the `oh-my-zsh.sh` from this PR as is.

```
/home/janke/.oh-my-zsh/oh-my-zsh.sh:76: command not found: compaudit

[oh-my-zsh] Automatically fix this? [y/N] n
/home/janke/.oh-my-zsh/oh-my-zsh.sh:107: command not found: compinit
[@ in ~]
$
```

To fix it, add the line `autoload -U compaudit compinit` at the beginning of all the new code in this PR.

Then it works like this, for me.

```
There are insecure directories:
/home/janke/.oh-my-zsh/plugins/nyan
/home/janke/.oh-my-zsh/plugins/themes
/home/janke/.oh-my-zsh/plugins/osx
/home/janke/.oh-my-zsh/plugins
/home/janke/.oh-my-zsh/plugins
/home/janke/.oh-my-zsh/plugins

[oh-my-zsh] Automatically fix this? [y/N] y
[oh-my-zsh] Fixed.
[@ in ~]
$
```

And the fix works. On next launch, I get a clean startup.

```
[@ in ~]
$ compaudit
[@ in ~]
$
```

**Comment by apjanke** [comment]
My umask is 022. I think the problem with mine is that I actually created my local `oh-my-zsh` repo in my Windows home dir using the Windows `git`, so the Cygwin umask didn't apply. My `~/.oh-my-zsh` is just a symlink pointing to that repo. Repos I created using the Cygwin `git` under the Cygwin `~` dir have acceptable.

Git doesn't store file permissions, and since OMZ is a per-user install, nobody's likely to be sharing access to a common `oh-my-zsh` git repo with a working copy. So I think fixing the in-repo dirs like this is probably fine. And in fact, necessary: the reason some of these plugin dirs are on `$fpath` is that they contain completion functions. So we don't want `compinit` skipping over them because of insecure permissions, which is what it does under `compinit -i`.

I think this means I was wrong about moving the test before the plugin `$fpath` loading: we want it to cover everything that the eventual `compinit` will see, because any bad dirs will affect the completeness of `compinit`'s output.

Paths with a group ownership other than `None` still might not have been intentionally modified. I still don't understand the Cygwin group mapping very well. But I think if you had simple given the user a different primary group, then that's what the group ownership for these dirs would be, regardless of whether the user intentionally fiddled with those particular files. And if `compaudit` is complaining about them, they really are misconfigured from the standpoint of Zsh. And whether they files are group writable could just be an accident of where the user created the repo.

Maybe what it comes down to is that on `oh-my-zsh` repo that you're loading OMZ from is intended to be a single-user installation (or a locked-down global installation). Group-based sharing of a "live" repo like that isn't supported. So `chmod`-ing the files in the repo sounds legit.

At this point I'm leaning toward thinking your current code's approach of just `chmod g-w` everything that `compaudit` complains about is the best approach, and done at the right point in the startup sequence..

**Comment by VinzNL** [comment]
> Could you post your broken .zcompdump file as a gist so we can use it for forensics and reproduction, too?

Of course, didn't think of that, it's certainly small enough:

```
#files: 716     version: 5.0.6

_comps=(
)

_services=(
)

_patcomps=(
)

_postpatcomps=(
)

_compautos=(
)


autoload -Uz

typeset -gUa _comp_assocs
_comp_assocs=( '' )
```

So basically it's empty.

**Comment by apjanke** [comment]
Wow, that is *really* broken. :)

**Comment by leycec** [comment]
> To fix it, add the line `autoload -U compaudit compinit` at the beginning of all the new code in this PR.

Not all humans are superb; you, however, are. I'm a bit surprised the current changeset worked for me at all, given that notable omission. *It shall be promptly fixed.*

> So we don't want `compinit` skipping over them because of insecure permissions, which is what it does under `compinit -i`... We want it to cover everything that the eventual `compinit` will see, because any bad dirs will affect the completeness of `compinit`'s output... Paths with a group ownership other than `None` still might not have been intentionally modified... Group-based sharing of a "live" repo like that isn't supported. So `chmod`-ing the files in the repo sounds legit.

**Right x 4.**

> I still don't understand the Cygwin group mapping very well.

Yeah – me neither. It doesn't help that the online Cygwin manual I *miserably* crawled through appeared to be desynchronized from Babun's current Cygwin version. I did note that the `None` group in `/etc/group` contained no users, despite the `groups` command clearly showing the `Administrator` user to belong to that group.

I suspect ACL shenanigans, in which case sanity really has gone out the window.

> At this point I'm leaning toward thinking your current code's approach of just `chmod g-w` everything that `compaudit` complains about is the best approach, and done at the right point in the startup sequence...

Did I mention that you were a superb human?

It's not simply that you advise me to do nothing. (I like that, though.) It's the voluminous analysis, complete with gritty worst-case catastrophes and low-level structural analysis. Luckily, I tripped over a bit of free time tonight. Let's see what I can do with it.

**Comment by apjanke** [comment]
I've added a listing of the user's `umask` and the permissions on `$fpath` directories to the `omz_diagnostic_dump` function in #3940, which may be able to help us diagnose some cases that are running in to this.

**Comment by apjanke** [comment]
I cannot reproduce the case where Cygwin installs `zsh` with insecure directories. My Cygwin zsh installation seems fine, and none of the linked issues or Stack Overflow questions contain enough information to actually reproduce the problem.

I am running Windows 7 with Cygwin, installing Cygwin "for all users" as user `root` which is a member of `Administrators`. I uninstalled and reinstalled Cygwin's `zsh` today after updating my whole Cygwin. I have `/etc/passwd` and `/etc/group` files generated (because that appears necessary in order to set users' default shells). The `$fpath` dirs will still fine; owner `root:root` and mode `655` on all of them. `compaudit` reports no issues, when run either as `root`, my non-Administrator `janke` user, or another Administrator user `root2`.
```
gwydion% ls -lad $fpath
ls: cannot access /usr/local/share/zsh/site-functions: No such file or directory
drwxr-xr-x+ 1 root root 0 Jun 28 17:19 /usr/share/zsh/5.0.8/functions
drwxr-xr-x+ 1 root root 0 Jun 28 17:19 /usr/share/zsh/site-functions
```

I'd feel better about pushing this out if we could test it against a broken installation that it's intended to fix.

Can you (or someone else who's experiencing this issue) tell me more about the specific setup you have where you ran in to this? E.g. which user did you install it as, which user is seeing the `compaudit` problems, which Windows version, are you a member of a domain, did you generate `/etc/passwd` and `/etc/group` files, etc.

I'll try to reproduce this by installing Babun.

**Comment by apjanke** [comment]
Oh, I can reproduce now. Simply installing Babun reproduces the problem. Babun repackages Cygwin and oh-my-zsh, and it's set up so the normal OMZ compinit process won't work with it.

Babun's default install contains insecure directories like this. It just installs to  `%USERPROFILE%\.babun` and doesn't do any permission setting on most of its directories. (`/usr/local` inside its bundled Cygwin is the only one it locks down.) `compaudit` sees those dirs as insecure, and if I delete the existing `~/.zcompdump` file, it'll start complaining upon new `zsh` session launches. The first time, it gives me a couple "unknown command or service" errors, and then that big spew of source code like you get.

```
compdef: unknown command or service: git
compdef: unknown command or service: grep
compdef: unknown command or service: git
{ ~ }  »                                                                                        ~
```

The [babun-core/plugins/oh-my-zsh/install_home.sh](https://github.com/babun/babun/blob/master/babun-core/plugins/oh-my-zsh/install_home.sh) script that Babun runs as part of initial installation has some code that generates the `.zcompdump` files using the insecure `compinit -u` that silently includes entries from the insecure directories that compaudit complains about.

```
if [ ! -f "$homedir/.zshrc" ]; then
	/bin/cp "$babun/home/.zshrc" "$homedir/.zshrc" 

	# fixing oh-my-zsh components
	zsh -c "source ~/.zshrc; rm -f \"$homedir/.zcompdump\"; compinit -u" &> /dev/null
	zsh -c "source ~/.zshrc; cat \"$homedir/.zcompdump\" > \"$homedir/.zcompdump-\"*" &> /dev/null	
fi
```

This means it's incompatible with how OMZ handles compinit, and if you ever delete your `.zcompdump` files, it'll break like this.

This is a Babun bug. We should report it to them and get them to fix it there.

I'm less enthusiastic about merging this permissions-check stuff in to the main OMZ code now, if Babun is the main case for it. I don't think it should be OMZ's job to hack around bugs introduced by downstream repackagers of OMZ and other components. This one seems like it should be easy enough to get fixed in Babun, and Babun looks immature enough that I bet we'll see more issues like this.

I'll see if I can also reproduce it under normal Cygwin.

**Comment by leycec** [comment]
**Deep analysis.** Thanks for delving into the unwieldy innards of Babun operation. It can't have been pleasant.

> This is a Babun bug. We should report it to them and get them to fix it there.

I absolutely agree that there *exists* the Babun bug you aptly identified. In the absence of other masochistic volunteers, I'll probably tackle that with a Babun-specific pull request in the coming week(s).

I do *not*, however, agree that `oh-my-zsh`'s constellation of `compdef` issues reduces to a convenient exoneration. This is *not* simply a Babun bug. `oh-my-zsh` inscrutably fails on startup in the general case of even a single insecure directory in `$fpath`. While Babun may well be the most reliable offender, this remains a commonplace `oh-my-zsh` issue afflicting `zsh` as well:

* [2014 `zsh` mailing list thread](http://www.zsh.org/mla/users/2014/msg00819.html): `zsh` under non-Babun Cygwin.
* [2015 blog post](http://www.faqssys.info/completions-stopped-working-after-upgrading-zsh): `oh-my-zsh` under OS X.
* [2015 `oh-my-zsh` issue](https://github.com/robbyrussell/oh-my-zsh/issues/3356): `oh-my-zsh` under OS X.
* [2015 `oh-my-zsh` issue comment](https://github.com/robbyrussell/oh-my-zsh/issues/3455#issuecomment-74574644): `oh-my-zsh` under non-Babun Cygwin.

**Neither OS X nor non-Babun Cygwin are Babun.** (That probably goes without saying.)

I'm convinced that this pervasively invasive issue will continue to beleaguer `oh-my-zsh` users under *all* supported platforms until a general-purpose fix is applied to `oh-my-zsh` itself. Which prompts the bushy eyebrow-raising question: "What fix?"

I'm convinced, again, that this pull request already supplies the only reasonable general-purpose fix – well, *nearly*. Before attempting completion initialization, `oh-my-zsh` startup should (arguably):

1. Detect and report the existence of insecure `$fpath` directories.
1. If such directories are found:
    1. Inform the user that completions will be *entirely* disabled until the reported insecurities are manually fixed.
    1. Automatically delete all `~/.zcompdump*` files.
    1. Avoid calling `compinit()`.

This patchset already implements **1.**, but should be improved to implement **2.** The contentious question is whether or not we retain the Cygwin-specific logic. Given the above URLs, I'm *reasonably* convinced that this issue still afflicts non-Babun Cygwin users – despite your inability to reproduce this on a sample testbed.

That said, I'm happy to compromise on this sore point. Since this issue *is* difficult to reproduce under non-Babun Cygwin installations, my untestable autofix entails some degree of risky danger. Unless anyone has strenuous objections (...*unlikeliness in the extreme*), I'll go ahead and excise the Cygwin-specific autofix. :hocho: 

The remaining logic should be sufficiently concise as to fit within the confines of the main `oh-my-zsh.sh` script. Ideally, we shouldn't need to offload anything into a utility `lib/` script.

**Only time will jauntily tell.**

**Comment by apjanke** [comment]
I agree. This goes beyond Babun, and we need to do something along these lines, even if we can't reproduce it. We see `compdef`-related breakage all the time here. And the current silent `compdef -i` is probably contributing to the breakage. Your "inform users / delete `~.zcompdump*` / don't `compinit`" sounds about right to me.

I'm a lot more comfortable with this if you remove the autofix that attempts to `chmod` directories that OMZ itself doesn't own. That sounds a lot less risky and invasive. (Especially if there are other libraries that have added their dirs to `$fpath`.) I think it will also make things less confusing when we're trying to hunt down the root cause of the insecure dirs on various platforms.

This is a big-deal change and we should test it before merging. I can do that on various platforms rigged to have insecure directories; I don't think it matters whether we can reproduce it "naturally" in this case. I'll also build up Windows 8.1 and Windows 10 DP boxes to test it on, since 8.1 seems to be where most of the Cygwin reports are coming from.

One other sticking point: the Oh My Zsh installer itself may need to be adjusted to lock down the `~/.oh-my-zsh` directory. Some of the items on `$fpath` come from within `~/.oh-my-zsh`, so if the cloned repo has open permissions, you'll hit this problem. For example, if you install OMZ with a `umask` of `002`, you will have insecure dirs.

```
eilonwy% umask 002
eilonwy% sh -c "$(wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
...
➜  ~  compaudit
There are insecure directories:
/Users/janke/.oh-my-zsh/plugins/git
/Users/janke/.oh-my-zsh/plugins
/Users/janke/.oh-my-zsh
```

And on Windows, I think the ACLs on the Cygwin home dir are also relevant. On Unix, just doing `umask 022` in the installer before the `git clone` is probably sufficient. Not sure if extra permissions stuff should be done on Windows. I'll see if I can figure it out with some testing there.

**Comment by leycec** [comment]
> I'm a lot more comfortable with this if you remove the autofix that attempts to chmod directories that OMZ itself doesn't own. That sounds a lot less risky and invasive. (Especially if there are other libraries that have added their dirs to $fpath.) I think it will also make things less confusing when we're trying to hunt down the root cause of the insecure dirs on various platforms.

No worries! That's compelling reasoning. Patching the Babun insecurity you kindly identified should go a long way toward correcting this for Cygwin users, anyway.

**The Cygwin autofix shall be mercilessly put to my rusty scalpel.**

> This is a big-deal change and we should test it before merging.

I'm in full agreement. (I'd *better* be.)

I have a few virtual boxes lying about that may be of interest, in addition to my principal Gentoo machine: **Ubuntu 15.04**, **OS X 10.6** (Snow Leopard), and **Windows XP Pro x64**. After I glom up a facsimile of a working solution, I'll try extending that to every machine at my disposal.

> One other sticking point: the Oh My Zsh installer itself may need to be adjusted to lock down the ~/.oh-my-zsh directory.

Quite right. That shouldn't be *too* arduous – at least under POSIX-compatible platforms.

> And on Windows, I think the ACLs on the Cygwin home dir are also relevant.

This is me gritting my teeth in misery.

> On Unix, just doing `umask 022` in the installer before the git clone is probably sufficient.

I suspect that's true. I suspect that's also simple. Which means it shall be done.

**Comment by leycec** [comment]
The work which transforms God. It is done.

**Comment by leycec** [comment]
The above two sentences probably failed to convey that this pull request has been revised to hopeful completion. (I was tired. Like, *really* tired.) As discussed:

* `oh-my-zsh` startup now handles insecure `$fpath` directories by deferring to a new `lib/compfix.sh` utility script. It's sweet and stuff.
* `oh-my-zsh` installation now coerces the `umask` to `022`. Two additional portability issues in the installer have *also* been addressed: [one fixed](https://github.com/leycec/oh-my-zsh/commit/8a06fbf3425be016220fb7832976fe4c4a06b2bc) and [one left unfixed](https://github.com/leycec/oh-my-zsh/commit/5fa5889bbaf406d82e062bdc354c19fa3766c8e1). There are a few sensible means of solving the latter issue, so I thought I'd leave it to consensus rather than do something horrible.

All changes have been rigorously tested under a Windows XP x64 Professional virtual box – but could always do with whatever additional eyeballs and testbeds you have at your disposal. :eyes:

**Comment by apjanke** [comment]
Cool. I will give this a test on a couple platforms.

We should probably `OR` the user's current umask with 022 instead of setting it to exactly 022, so if they have it set to something more restrictive, we respect that.

```
# Per-digit bitwise OR example
old_umask=$(umask)
new_umask=$old_umask[1]$(( old_umask[2] | 2))$(( old_umask[3] | 2))
```

**Comment by leycec** [comment]
> We should probably OR the user's current umask with 022 instead of setting it to exactly 022, so if they have it set to something more restrictive, we respect that.

Smart reasoning... and you're quite right, of course. It shall be done.

That's a compelling example, too. I'm a bit unconvinced, however, that Bourne shell provides a means of performing bitwise operations – either via a builtin *or* external command. Bourne shell doesn't appear to support a variant of `zsh`-specific `$((...))`-style arithmetic substitutions. Moreover, the external `expr` command typically used for arithmetic operations in Bourne shell scripts doesn't appear to support anything other than simplistic integer math.

This is probably yet another compelling argument for using anything *other* than Bourne shell for `oh-my-zsh` installation. Even `bash` would be preferable.

That said, I'm probably missing something. Maybe there is a way to effect this in raw, low-level Bourne shell?

**Comment by apjanke** [comment]
> I'm a bit unconvinced, however, that Bourne shell offers an equivalent means of performing bitwise operations 

D'oh! Busted; yeah that's `zsh`/`bash` specific arithmetic code. Uh, I dunno how to do this aside from actually writing out a truth table. Feasible since you only need to cover 0-7 and certain values for the case of `umask`: start with 2; if user's value is >=4, add 4; if it's odd, add 1. Feasible but ugly. I don't have any better ideas at the moment.

**Comment by leycec** [comment]
> I dunno how to do this aside from actually writing out a truth table.

It's like my pappy used to say: "If you have to write out a truth table, you're using the wrong tool."

I agree with my pappy.

> Feasible since you only need to cover 0-7 and certain values for the case of umask: start with 2; if user's value is >=4, add 4; if it's odd, add 1. Feasible but ugly.

**Oh. My. God.** I'd rather *not* receive a premature pulmonary embolism. (All in due time. It'll come.)

On grounds of this "solution" **(A)** irreparably degrading mental, physical, and spiritual health, **(B)** inviting international ridicule from the blogosphere (see: "What is [4chan /g/](http://boards.4chan.org/g/)?"), **(C)** conflicting with basic moral decency, and **(D)** exceeding the entirety of the current installation script in both length and general uselessness, I politely prefer *not* to implement this. I also don't quite follow the prior advice – presumably due to mental degeneracy and/or lunacy incurred by merely contemplating implementing this.

_**Edit:** After implementing the sample "solution" below, I now follow the prior advice. I wish I didn't._

If (hypothetically speaking) I were to implement this (which I'm non-hypothetically not), I'd probably contemplate something resembling:

```
# Current umask.
umask_old=`umask`

# User, group, and other components of such umask.
umask_old_user=`expr ${umask_old} / 10 / 10`
umask_old_group=`expr ${umask_old} / 10 % 10`
umask_old_other=`expr ${umask_old} % 10`

# New umask, beginning with the user component of the current umask unchanged.
umask_new="${umask_old_user}"

# Append the group component of the current umask, modified to prohibit
# writability if currently permitted or otherwise unchanged.
if [ ${umask_old_group} -ne 2 -a \
     ${umask_old_group} -ne 3 -a \
     ${umask_old_group} -ne 6 -a \
     ${umask_old_group} -ne 7 ]
then umask_new="${umask_new}`expr ${umask_old_group} + 2`"
else umask_new="${umask_new}${umask_old_group}"
fi

# Append the other component of the current umask, modified to prohibit
# writability if currently permitted or otherwise unchanged.
if [ ${umask_old_other} -ne 2 -a \
     ${umask_old_other} -ne 3 -a \
     ${umask_old_other} -ne 6 -a \
     ${umask_old_other} -ne 7 ]
then umask_new="${umask_new}`expr ${umask_old_other} + 2`"
else umask_new="${umask_new}${umask_old_other}"
fi
```

*Yeah.* I tested it. It works, assuming you don't blink at it.

But I think we'd all rather *not* drag the good name of `oh-my-zsh` through the troll-infested mud that is professional Internet heckling. For similar reasons, I'd also rather *my* (not necessarily) good name be permanently attached to this. I feel woefully inadequate enough as it is.

_**Behold!** The lidless eye of Bourne Shell Sauron induces spastic tremors in all what finger its deathless void._

> I don't have any better ideas at the moment.

I have a better idea. You're gonna love it. **Don't use Bourne shell.**

**Comment by apjanke** [comment]
That's... even grosser than I was expecting.

But wait a minute! I was reading through the doco and [*there's a symbolic form of `umask` call*](https://en.wikipedia.org/wiki/Umask#Setting_the_mask_using_symbolic_notation) that lets you just apply deltas to the current `umask` value. It's in the [1997 UNIX spec](http://pubs.opengroup.org/onlinepubs/007908799/xcu/umask.html) so it should be available pretty much everywhere.

```
umask g-w,o-w
```

Tested on OS X under `sh`:

```
sh-3.2$ umask 000
sh-3.2$ umask
0000
sh-3.2$ umask g-w,o-w
sh-3.2$ umask
0022
sh-3.2$ umask g-w,o-w
sh-3.2$ umask
0022
sh-3.2$
```

I am finding your reasoning for switching to `zsh` for the installer scripts pretty persuasive. I gotta mull it over a bit but I think I would get behind an initiative to do that. (I'm going to delve through the old issues and see if there's existing discussion on it.) But that's a larger change and well above my pay grade on this project; would probably be harder to get done than this change on its own.

**Comment by leycec** [comment]
>  I was reading through the doco and there's a symbolic form of `umask` call that lets you just apply deltas to the current `umask` value.

    Palm strikes forehead.
    Slapping sound ensues.
    Bad haiku is bad.

`umask g-w,o-w` owns me. Therefore, it's going in as a single-line replacement for the current brute-force `umask 022` approach. Thanks for poring through the arcane mundanities of the 1997 UNIX specification.

*Where did you even find that thing?*

> But that's a larger change and well above my pay grade on this project;

You can imagine what my pay grade might look like. It's not pretty.

> would probably be harder to get done than this change on its own.

It might be simpler than any human yet imagines. As with most modern-day maladies, the roadblocks appear to be *institutional* rather than *technical*. As `zsh` is a strict superset of `sh`, substituting `sh -c` for `zsh -c` in the `README.md` installation instructions should technically suffice to make the switch.

**That's it.** No additional repository-level changes should be required. We wouldn't even have to rename `install.sh` to `install.zsh`, though that would probably be a nice idea.

*Or would it?* :sun_with_face:

**Comment by leycec** [comment]
**Updated.** The ["Installation-time portability issue identified."](https://github.com/leycec/oh-my-zsh/commit/5fa5889bbaf406d82e062bdc354c19fa3766c8e1) commit has been killed, while the  commit has been updated to enforce an installation-time `umask g-w,o-w`.

**Comment by apjanke** [comment]
Excellent.

> Where did you even find that thing?

Well, the OS X `umask` page doesn't have much detail on it. So I was Googling around for "combining umasks posix shell" etc, which somehow led me to an old *Solaris* man page for `umask`, which has lots of detail and discusses the symbolic form. Go figure. Once I knew of its existence and the word for it, finding the Wikipedia reference and so on was easy. I only went to the Unix spec once I was trying to figure out just how portable it would be.

Wish I had done this research earlier. I could have been using this symbolic `umask` for the last ten years or so.

>>  would probably be harder to get done than this change on its own.
>
> It might be simpler than any human yet imagines. 

Yeah. I meant "harder" in terms of the institutional aspects of getting the change tested and accepted. Agreed that it's basically swapping `sh` for `zsh` in the instructions. (However, copies of the instructions are out in the wild, on StackOverflow answers, or in people's shell histories, or even propagated to scripts etc etc. So you might have to add some checking and a "please switch to `zsh`" to get it to fail gracefully if we start requiring `zsh` for it.)

> As `zsh` is a strict superset of `sh`

In a functional sense, yes, but the default syntax and behavior is not the same. E.g. basic stuff like word splitting differs significantly, some strings that would be literals in `sh` get parsed as variable refs in `zsh` due to the presence of array variables and expansion/globbing modifiers, extra `zsh` builtins may have different behavior from the commands `sh` finds, etc, etc. I don't think it'd be an issue in this case, but it's something to be aware of: anything you can do in `sh`, you can do in `zsh`, but if you just take an arbitrary script and run it under `zsh` instead of `sh`, you are not guaranteed to get the same results. You at least need an `emulate`.

**Comment by leycec** [comment]
> I could have been using this symbolic `umask` for the last ten years or so.

I can only commiserate. Symbolic `umask` is a UNIX diamond in the rough. :gem: 

> So you might have to add some checking and a "please switch to `zsh`" to get it to fail gracefully if we start requiring `zsh` for it.

Quite a good idea. If and (more hopefully) when the team contemplates a formal switch-over, I'd be happy to jury-rig up a pull request addressing that.

> In a functional sense, yes, but the default syntax and behavior is not the same.

Quite right. I neglected to preface the bald-faced lie that "As `zsh` is a strict superset of `sh`..." with the caveat "Under `emulate -R sh,` ...". Though even *that* isn't strictly true, is it? I'd be curious to see how closely `zsh` emulation aligns with oddball edge-cases in Bourne shell syntax and semantics.

*Anyways* – a perpendicular (and probably uninteresting) tangent for an emptier weekend. For now, a copious pile of video games and overly caffeinated drinks awaits!

**Comment by leycec** [comment]
**Oh, save me, Jebus!**[*](https://www.youtube.com/watch?v=MSC11hLbM1w)

At long last, the grisly moment we all knew was coming (...but really hoped wasn't). I've identified the underlying cause of the `('Babun'|'Cygwin')` insecurity you [recently documented in voluminous detail](https://github.com/babun/babun/issues/380), @apjanke. It ain't pretty.

To the astonishment of all involved (*mostly me*), it isn't Babun's or Cygwin's fault. It isn't even `oh-my-zsh`'s fault. **It's `zsh`'s fault.**

To compound matters, any reasonable solution to this issue requires adding a new core `zsh` module and hence is sufficiently non-trivial as to be done approximately never. Yes, it's that bad.

To document why, I first need to document how POSIX permissions and non-POSIX ACL permissions incestuously relate. You already know all this. (You're just that good.) So, this is mostly for the benefit of the ACL layman – meaning me in five months and/or the throes of a hard weekend of ouzo-fed inebriation.

## What's an ACL, Daddy?

I'm glad you asked, Billy.

The Anterior Cruciate Ligament (ACL) is an essential knee ligament. It doesn't like arrows. It appears to like amica and castor oil. I have no idea what either of those two things are.

It's also an Access Control List (ACL). For our purposes, forget knees. ACLs are a [strict superset](http://linux.die.net/man/5/acl) of traditional POSIX file permissions. (They actually are.) For probably inane and contemptible reasons, the POSIX ACL draft standards were [formally withdrawn](https://doc.opensuse.org/documentation/html/openSUSE_121/opensuse-security/cha.security.acls.html) before being accepted. Thankfully, everyone ignored that.

All modern Unix-like platforms (including the BSDs, Linux, and OS X) support these standards to a fair degree of compliance, which is a refreshing change. While (naturally) _no_ modern Windows platforms do, Microsoft's selective reinterpretation of the concept approximates these standards closely... enough. Cygwin does a clean hatchet job of preserving the Windows security model into the almost-POSIX ACL world. 

While comparatively rare under desktop Linux environments, ACLs are omnipresent under _all_ modern Windows environments. And this is where Our Troubles starts.

## So `zsh` Loves ACLs, Right?

**Nope! `zsh` doesn't know anything about ACLs.**

`zsh` _does_ know something about every other security model on this forelorn planet, which it exposes via core `zsh` modules (i.e., shared libraries bundled with `zsh` dynamically loadable at runtime). This includes extended attributes (`zsh/attr`), POSIX capability sets (`zsh/cap`), and traditional POSIX permissions (`zsh/stat`). Ideally, there would exist a similar module exposing almost-POSIX ACLs (say, oh-I-don't-know, `zsh/acl`). There doesn't.

Is that a problem? Yes. Yes, it is.

Because `zsh` doesn't know anything about ACLs, `compaudit` doesn't know anything about ACLs. Because `compaudit` doesn't know anything about ACLs, `compaudit` incorrectly identifies secure ACLs on `$fpath` directories as insecure. Which means that this issue actually afflicts _all_ platforms supporting almost-POSIX ACLs. Which is basically _all_ of them. Which means, in turn, that the output of `compaudit` is inherently untrustworthy if one or more `$fpath` directories have non-trivial ACLs (i.e., ACLs with more than the three traditional POSIX entries `user`, `group`, and `other` and hence _not_ losslessly reducible to traditional POSIX permissions).

Above, we wildly claimed that "ACLs are omnipresent under _all_ modern Windows environments." It's actually true. Pretty much all paths on NTFS filesystems have complex and hence non-trivial ACLs, including _all_ `$fpath` directories under Cygwin. Which means that **`compaudit` output is _always_ inherently untrustworthy under Cygwin.** Which probably means that option `-u` (ignoring `compaudit` output) should be conditionally passed to the call to `compinit()` in `oh-my-zsh.sh` if and only if the current platform is Cygwin.

## Wait. Why Does `compaudit` Ignoring ACLs Make Badness, Again?

Let's get esoteric.

`compaudit` leverages `zsh/stat` facilities to unconditionally access traditional POSIX permissions for all `$fpath` directories – even for directories with non-trivial ACLs, which (again) is _all_ of them under Cygwin. But ACLs are a superset of POSIX permissions! Attempting to reduce the former to the latter necessarily entails loss, which is bad jujube. To preserve POSIX semantics during this reduction (...as much as feasible, anyway), the designers of the almost-POSIX ACL standards adopted the following sensible stance:

* For paths with non-trivial ACLs, the traditional POSIX user, group, or other permissions entry reported by the kernel _must_ be the logical conjunction (i.e., AND) of:
  * The logical disjunction (i.e., OR) of _all_ ACL user, group, or other entries for that path (respectively) and
  * That path's mask if any _or_ `rwx` otherwise.

It hurts bad! Let's stumble through a simple applicable example. For vanilla Cygwin installations on vanilla Windows installations, `/usr/share/zsh` usually has a non-trivial ACL and corresponding POSIX permissions resembling:

```
$ getfacl /usr/share/zsh
# file: /usr/share/zsh
# owner: Administrator
# group: None
user::rwx
group::---
group:SYSTEM:rwx
group:Administrators:rwx
mask:rwx
other:---
default:user::rwx
default:group::---
default:group:SYSTEM:rwx
default:group:Administrators:rwx
default:mask:rwx
default:other:---
$ ls -ld /usr/share/zsh
drwxrwx---+ 1 Administrator None 0 Jun 23 11:08 /usr/share/zsh
```

Note the `+` suffixing the POSIX permissions list, signifying this path to have a non-trivial ACL and this POSIX permissions list little to no correspondence to reality. Moreover, note the fake `None` group permissions reported by `ls` (i.e., `rwx`) to *completely differ* from the actual `None` group permissions reported by `getfacl` (i.e., `---`), signifying traditional POSIX permissions to be utterly useless for evaluating the security of paths with non-trivial ACLs.

**Holy balls.** How did it come to this? Simple. The kernel and hence `ls` has to report _something_, even if that something is a complete lie. (Which it is.) In the above case, it lyingly reports the POSIX group permissions for `/usr/share/zsh` to be:

    (--- || rwx || rwx) && rwx = rwx

Thus was Hell built. `compaudit` _thinks_ it knows what it's talking about, but is actually a brick short of a full load. Much like me on Mondays.

## Oh, God.

*Yeah.*

On the bright side, nothing above invalidates this pull request. `oh-my-zsh` still needs to catch `$fpath` insecurities in a sane manner and this pull request largely achieves that... at least on systems where all `$fpath` directories have trivial or no ACLs. In practice, that should be most BSD and Linux systems. As for OS X, I am Clueless Joe. [Read: Someone should probably investigate OS X. Not me.]

As for Cygwin, I modestly repeat the above proposal of conditionally passing option `-u` to `compinit()` in `oh-my-zsh.sh` if the current platform is Cygwin... at least until the `zsh` community adds ACL- and Cygwin-specific awareness to `compaudit()`. Since that probably requires the construction of a new `zsh/acl` module, I wouldn't hold my wheezy breath.

Thus dies another kitten in Stephen Harper's [alien arms](http://thingsharperdoestoseemhuman.tumblr.com/post/4218233970/holding-kittens).

**Comment by robbyrussell** [comment]
Thanks for all your had work (and explanation) here! :blue_heart:

**Comment by mcornella** [comment]
Probably related (I thought we had this automated?): #4378

**Comment by stucki** [comment]
It seems like this change causes a lot of new problems. Can you please check #4378 and 4388? Thank you!

**Comment by apjanke** [comment]
I may see the problem here.

```
# If completion insecurities exist, warn the user without enabling completions.
if ! compaudit &>/dev/null; then
  # This function resides in the "lib/compfix.zsh" script sourced above.
  handle_completion_insecurities
# Else, enable and cache completions to the desired file.
else
  compinit -d "${ZSH_COMPDUMP}"
fi
```

That `compinit` is in the `else` branch. In the case where it finds insecurities, it tries to fix them, but doesn't call `compinit` in that session.

Maybe the fix is as simple as pulling the `compinit` out of the `else` block, so it tries to run once `handle_completion_insecurities` has tried fixing things up.

```
if ! compaudit &>/dev/null; then
  # This function resides in the "lib/compfix.zsh" script sourced above.
  handle_completion_insecurities
fi
compinit -d "${ZSH_COMPDUMP}"
```

**Comment by apjanke** [comment]
Oh, that's not the only problem: per #4388, looks like the `-i` is still required in order to play nicely with `sudo` or other situations where your effective user id is not the same as the one that owns your completion directories. See discussion there.

**Comment by mcornella** [comment]
Agree with the assesment that `compinit` is not called if `compaudit` returns errors. Let's solve this one real quick. 

Regarding the `sudo` breakage, perhaps we can have a special case where we ignore `compinit` insecure directories when the user is `root` and insecure directories are owned by `$SUDO_USER`. It turns out `sudo` sets `$SUDO_UID` and `$SUDO_USER`, so perhaps we can play with that. 

FWIW though, putting the `compinit` statement outside of the `else` branch will ask users if they want to continue loading those insecure directories, so it will be a partial fix already.

@leycec what do you think?

**Comment by mcornella** [comment]
I've submitted a quick hack at https://github.com/mcornella/oh-my-zsh/commit/3b49b29fd60d34987359589daa2aa4a62c2adbeb, what do you guys think?

**Comment by apjanke** [comment]
Yeah. I like the quick hack putting it outside the `else`. Should probably also change the error message from `lib/compfix` so it's not lying about disabling completions.

```
[oh-my-zsh] Insecure completion-dependent directories detected:
drwxr-xrwx  4 janke  staff  136 Sep 23 18:48 /Users/janke/.oh-my-zsh/plugins/git
[oh-my-zsh] For safety, completions will be disabled until you manually fix all
[oh-my-zsh] insecure directory permissions and ownership and restart oh-my-zsh.
[oh-my-zsh] See the above list for directories with group or other writability.
```

Alternately, could stick the `-i` back in to the `compinit` call, so users would just see the warnings from `lib/compfix`, but completion would still run.

WRT the `sudo` breakage, maybe just adding `-i` whenever you're doing `sudo` (and maybe checking for "effective_uid != actual uid" for the `su` case) is the right approach. You'll get the same breakage when `sudo`-ing to non-root users as well. I think we're just seeing it with `root` in particular because that is the most common `sudo`/`su` use case.

I thought showing users the nag about insecure directories and getting them to fix it etc was intentional as part of this change, and that it's done because the auto-fix reduces the number of cases where you get a spurious nag. Advantage is that now "my completion isn't working as expected" would get identified and automatically diagnosed in more cases. (I don't have an opinion on which way is better; just saying I thought it was expected with this change.)

**Comment by apjanke** [comment]
Oh, wait: I misunderstood this somewhat. Despite the "Repair" in this PR's description, it doesn't actually do any permission changing to try to fix insecure directories automatically. It just disables completion and removes old `zcompdump` files if it finds insecure directories.
